# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

  
# http server autoconfig
#
server:
  port: 8081

#security:
#  ignored: /webHook/*
#  user:
#    name: admin
#    password: 123456

logging:
  config: classpath:config/logback.xml
  path: ../logs
  level:
    root: INFO

swagger:
  enabled: true
  title: gitlab-code-statistics
  description: gitlab-code-statistics接口规范
  version: 1.0

gitlab:
  url: http://192.168.199.32:8004
  user: root
  pwd: 12345678  
 
# mongodb 配置
spring:
  data:
    mongodb:
        uri: mongodb://localhost:27017/gitstats
  devtools:
    restart:
      additional-paths: src\main\resources\static
  resources:
    chain:
      html-application-cache: true
      
gitstats:
  autofill: false
  
      
#hook配置 项目token
#hook:
#  secretToken:

  
 